# TODO(phase 0.2/2): Kafka Connect + Debezium plugin.
#   FROM confluentinc/cp-kafka-connect:7.6.1
#   ENV CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components
#   RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
FROM confluentinc/cp-kafka-connect:7.6.1
